### ISSUE TITLE
CMS 4 ADMIN SIGNOUT issue

### ISSUE THREAD

**Issue by pooria-ghorbani** [django-cms/cms-template#2]
**CMS 4 ADMIN issue**
when signout of admin , do not signout with error [22/Dec/2023 12:23:33] "GET /en/admin/logout/ HTTP/1.1" 405 0

**Comment by fsbraun** [comment]
@pooria-ghorbani  thanks for raising this issue. I assume you use Django by 5.0 which is installed by this template?

**Comment by pooria-ghorbani** [comment]
thank too , i use django==4.2

**Comment by pooria-ghorbani** [comment]
i think pattern of urls.py not corrected!

**Comment by fsbraun** [comment]
@pooria-ghorbani I can reproduce the error with Django 5.0, but **not** with Django 4.2. Can you double-check for the project?

The `urls.py` looks ok, but as of Django 5.0, the admin logout URL (which is called) only accepts POST requests.

**Comment by pooria-ghorbani** [comment]
i update django to --v 5 but error again , and server log : [23/Dec/2023 11:29:41] "GET /admin/logout/ HTTP/1.1" 405 0 
and in consol request error : Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

**Comment by fsbraun** [comment]
I've created a fix. You can install it with `pip install git+https://github.com/fsbraun/django-cms@fix/logout-django-5-0`. With the fix, the error message should not appear.

**Comment by pooria-ghorbani** [comment]
thank you bro, you are best of django-cms , i love u men

**Comment by fsbraun** [comment]
Fix with the django-cms==4.1.0 release
